[package]
name = "cargo-libafl-runtime"
version = X
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "The runtime lib for cargo-libafl"
repository = "https://github.com/AFLplusplus/cargo-libafl"
edition = "2021"

[workspace]

[dependencies]
libafl = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "8eab7d6063ec8dce1461ded6bdb8b97a1475f695" }
libafl_targets = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "8eab7d6063ec8dce1461ded6bdb8b97a1475f695", features = ["sancov_8bit", "sancov_cmplog"] }
mimalloc = { version = "*", default-features = false }
structopt = "0.3.25"
portpicker = "0.1.1"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[lib]
crate-type = ["staticlib", "rlib"]
